[package]
name = "crabs"
version = "0.1.0"
authors = ["stoyaneft <stoyaneft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
rand = "0.7"